import { CropType, DiseaseInfo } from './types';

export const CROPS: { id: CropType; nameEn: string; nameUr: string; icon: string }[] = [
  { id: 'wheat', nameEn: 'Wheat', nameUr: 'گندم', icon: '🌾' },
  { id: 'rice', nameEn: 'Rice', nameUr: 'چاول', icon: '🥣' },
  { id: 'cotton', nameEn: 'Cotton', nameUr: 'کپاس', icon: '☁️' },
  { id: 'sugarcane', nameEn: 'Sugarcane', nameUr: 'گنا', icon: '🎋' },
  { id: 'maize', nameEn: 'Maize', nameUr: 'مکئی', icon: '🌽' },
  { id: 'tomato', nameEn: 'Tomato', nameUr: 'ٹماٹر', icon: '🍅' },
  { id: 'potato', nameEn: 'Potato', nameUr: 'آلو', icon: '🥔' },
  { id: 'onion', nameEn: 'Onion', nameUr: 'پیاز', icon: '🧅' },
  { id: 'chilli', nameEn: 'Chilli', nameUr: 'مرچ', icon: '🌶️' },
  { id: 'mango', nameEn: 'Mango', nameUr: 'آم', icon: '🥭' },
  { id: 'citrus', nameEn: 'Citrus', nameUr: 'کنو', icon: '🍊' },
  { id: 'sunflower', nameEn: 'Sunflower', nameUr: 'سورج مکھی', icon: '🌻' },
];

export const OFFLINE_DISEASES: Record<CropType, Record<string, DiseaseInfo>> = {
  wheat: {
    'Leaf Rust': {
      nameEn: 'Leaf Rust',
      nameUr: 'گندم کی کنگئی',
      explanation: 'Leaf rust is a fungal disease that affects wheat stems, leaves and grains. It can cause significant yield loss if not treated immediately.',
      explanationUr: 'لیف رسٹ ایک فنگس کی بیماری ہے جو گندم کے تنے، پتوں اور دانوں پر اثر انداز ہوتی ہے۔ اگر فوری علاج نہ کیا جائے تو یہ پیداوار میں نمایاں کمی کا باعث بن سکتی ہے۔',
      pesticideBrand: 'Propiconazole 25% EC',
      pesticideBrandUr: 'پروپیکونازول 25% ای سی',
      pricePkr: 1450,
      mixingRatio: '200ml / Acre',
      mixingRatioUr: '200 ملی لیٹر فی ایکڑ',
      sprayTime: 'Early morning or late evening',
      sprayTimeUr: 'صبح سویرے یا شام گئے',
      yieldLossPercent: '35% - 40%',
      financialLossPkr: 45000,
      warningSigns: ['Orange-yellow spots on leaves', 'Brown powder rubbing off on hands', 'Premature drying of leaf tips'],
      warningSignsUr: ['پتوں پر نارنجی زرد دھبے', 'ہاتھوں پر لگنے والا بھورا سفوف', 'پتوں کے نوکوں کا وقت سے پہلے خشک ہونا'],
    },
    'Yellow Rust': {
      nameEn: 'Yellow Rust',
      nameUr: 'زرد کنگئی',
      explanation: 'A fungal disease showing yellow stripes on leaves. It thrives in cool, moist weather.',
      explanationUr: 'ایک فنگس کی بیماری جو پتوں پر زرد رنگ کی دھاریاں دکھاتی ہے۔ یہ ٹھنڈے اور مرطوب موسم میں تیزی سے پھیلتی ہے۔',
      pesticideBrand: 'Nativo (Bayer)',
      pesticideBrandUr: 'نیٹیوو (بائر)',
      pricePkr: 3200,
      mixingRatio: '65g / Acre',
      mixingRatioUr: '65 گرام فی ایکڑ',
      sprayTime: 'During low wind',
      sprayTimeUr: 'کم ہوا کے وقت',
      yieldLossPercent: '20% - 50%',
      financialLossPkr: 60000,
      warningSigns: ['Yellow pustules in stripes', 'Leaf chlorosis', 'Stunted growth'],
      warningSignsUr: ['پتوں پر زرد رنگ کی دھاریاں', 'پتوں کا پیلا پڑنا', 'پودے کا قد چھوٹا رہنا'],
    },
    'Powdery Mildew': {
      nameEn: 'Powdery Mildew',
      nameUr: 'سفیدک',
      explanation: 'White powdery spots on leaves and stems.',
      explanationUr: 'پتوں اور تنے پر سفید پاؤڈر جیسے دھبے نمودار ہوتے ہیں۔',
      pesticideBrand: 'Score (Syngenta)',
      pesticideBrandUr: 'اسکور (سینجنٹا)',
      pricePkr: 2100,
      mixingRatio: '100ml / 100L water',
      mixingRatioUr: '100 ملی لیٹر فی 100 لیٹر پانی',
      sprayTime: 'Morning',
      sprayTimeUr: 'صبح',
      yieldLossPercent: '10% - 25%',
      financialLossPkr: 25000,
      warningSigns: ['White flour-like patches', 'Curling leaves', 'Grayish fungus growth'],
      warningSignsUr: ['آٹے جیسے سفید دھبے', 'پتوں کا مڑنا', 'سرمئی رنگ کی الی'],
    },
    'Loose Smut': {
      nameEn: 'Loose Smut',
      nameUr: 'کانی',
      explanation: 'Grain heads replaced by black mass of spores.',
      explanationUr: 'گندم کے سٹے دانوں کے بجائے سیاہ سفوف سے بھر جاتے ہیں۔',
      pesticideBrand: 'Tebuconazole',
      pesticideBrandUr: 'ٹیبوکونازول',
      pricePkr: 1800,
      mixingRatio: 'Seed treatment (2g/kg)',
      mixingRatioUr: 'بیج کا زہر (2 گرام فی کلو)',
      sprayTime: 'Seed stage',
      sprayTimeUr: 'بیج لگانے سے پہلے',
      yieldLossPercent: '5% - 15%',
      financialLossPkr: 15000,
      warningSigns: ['Black powdery heads', 'Absence of grains', 'Dark colored stalks'],
      warningSignsUr: ['سیاہ پاؤڈر والے سٹے', 'دانوں کی جگہ کالا سفوف', 'کالے رنگ کے پودے'],
    },
  },
  rice: {
    'Brown Spot': {
      nameEn: 'Brown Spot',
      nameUr: 'بھورا دھبہ',
      explanation: 'Oval brown spots on leaves.',
      explanationUr: 'پتوں پر بیضوی شکل کے بھورے دھبے نمودار ہوتے ہیں۔',
      pesticideBrand: 'Difend',
      pesticideBrandUr: 'ڈیفینڈ',
      pricePkr: 1650,
      mixingRatio: '250ml / Acre',
      mixingRatioUr: '250 ملی لیٹر فی ایکڑ',
      sprayTime: 'Late afternoon',
      sprayTimeUr: 'سہ پہر',
      yieldLossPercent: '10% - 40%',
      financialLossPkr: 35000,
      warningSigns: ['Oval brown spots', 'Yellow halo around spots', 'Drying of leaves'],
      warningSignsUr: ['بیضوی بھورے دھبے', 'دھبوں کے گرد زرد ہالہ', 'پتوں کا خشک ہونا'],
    },
    'Blast': {
      nameEn: 'Blast',
      nameUr: 'بلاسٹ',
      explanation: 'Diamond shaped lesions on leaves.',
      explanationUr: 'پتوں پر ہیرے کی شکل کے زخم یا نشانات بنتے ہیں۔',
      pesticideBrand: 'Amistar Top',
      pesticideBrandUr: 'ایمسٹار ٹاپ',
      pricePkr: 3800,
      mixingRatio: '200ml / Acre',
      mixingRatioUr: '200 ملی لیٹر فی ایکڑ',
      sprayTime: 'Calm morning',
      sprayTimeUr: 'پرسکون صبح',
      yieldLossPercent: '30% - 70%',
      financialLossPkr: 85000,
      warningSigns: ['Spindle shaped spots', 'Gray centers', 'Neck rot'],
      warningSignsUr: ['تکونی شکل کے دھبے', 'دھبوں کا درمیانی حصہ سرمئی', 'منجر کا گلنا'],
    },
    'Sheath Blight': {
      nameEn: 'Sheath Blight',
      nameUr: 'شیٹھ بلائٹ',
      explanation: 'Large spots on leaf sheaths near water line.',
      explanationUr: 'پانی کی سطح کے قریب پتوں کی تہوں پر بڑے دھبے بنتے ہیں۔',
      pesticideBrand: 'Validamycin',
      pesticideBrandUr: 'ویلیڈامائیسن',
      pricePkr: 1200,
      mixingRatio: '400ml / Acre',
      mixingRatioUr: '400 ملی لیٹر فی ایکڑ',
      sprayTime: 'Evening',
      sprayTimeUr: 'شام',
      yieldLossPercent: '20% - 30%',
      financialLossPkr: 40000,
      warningSigns: ['Large grayish lesions', 'Snake-skin pattern', 'Lodging'],
      warningSignsUr: ['بڑے سرمئی دھبے', 'سانپ کی کھال جیسے نشان', 'فصل کا گرنا'],
    },
    'Bacterial Leaf Blight': {
      nameEn: 'Bacterial Leaf Blight',
      nameUr: 'بیکٹیریل بلائٹ',
      explanation: 'Water-soaked lesions on leaves turning yellow.',
      explanationUr: 'پتوں پر پانی سے بھرے نشانات جو بعد میں پیلے ہو جاتے ہیں۔',
      pesticideBrand: 'Copper Hydroxide',
      pesticideBrandUr: 'کاپر ہائیڈرو آکسائیڈ',
      pricePkr: 2500,
      mixingRatio: '500g / Acre',
      mixingRatioUr: '500 گرام فی ایکڑ',
      sprayTime: 'After rain',
      sprayTimeUr: 'بارش کے بعد',
      yieldLossPercent: '20% - 60%',
      financialLossPkr: 70000,
      warningSigns: ['Wavy yellow leaf margins', 'Bacterial ooze', 'Wilting seedlings'],
      warningSignsUr: ['پتوں کے کناروں کا پیلا ہونا', 'پتوں سے رطوبت کا نکلنا', 'پنیری کا مرجھانا'],
    },
  },
  cotton: {
    'Alternaria Leaf Spot': {
      nameEn: 'Alternaria Leaf Spot',
      nameUr: 'الٹرنیریا دھبہ',
      explanation: 'Small brown concentric spots on leaves.',
      explanationUr: 'پتوں پر چھوٹے بھورے رنگ کے گول دھبے بنتے ہیں۔',
      pesticideBrand: 'Antracol',
      pesticideBrandUr: 'انٹراکال',
      pricePkr: 1900,
      mixingRatio: '500g / Acre',
      mixingRatioUr: '500 گرام فی ایکڑ',
      sprayTime: 'Sunrise',
      sprayTimeUr: 'طلوع آفتاب',
      yieldLossPercent: '15% - 25%',
      financialLossPkr: 30000,
      warningSigns: ['Circular brown spots', 'Concentric rings', 'Falling leaves'],
      warningSignsUr: ['گول بھورے دھبے', 'دھبوں میں دائرے', 'پتوں کا گرنا'],
    },
    'Cotton Leaf Curl Virus': {
      nameEn: 'Cotton Leaf Curl Virus',
      nameUr: 'پتہ مروڑ وائرس',
      explanation: 'Upward or downward leaf curling and thickening of veins.',
      explanationUr: 'پتوں کا اوپر یا نیچے مڑنا اور رگوں کا موٹا ہونا۔',
      pesticideBrand: 'Confidor (for whitefly)',
      pesticideBrandUr: 'کونفیڈور (سفید مکھی کے لیے)',
      pricePkr: 1400,
      mixingRatio: '250ml / Acre',
      mixingRatioUr: '250 ملی لیٹر فی ایکڑ',
      sprayTime: 'Early morning',
      sprayTimeUr: 'صبح سویرے',
      yieldLossPercent: '40% - 90%',
      financialLossPkr: 120000,
      warningSigns: ['Upward curling of leaves', 'Thickened veins', 'Stunted growth'],
      warningSignsUr: ['پتوں کا اوپر مڑنا', 'رگوں کا موٹا ہونا', 'پودے کا قد رکنا'],
    },
    'Boll Rot': {
      nameEn: 'Boll Rot',
      nameUr: 'ٹینڈوں کا گلنا',
      explanation: 'Rotting of cotton bolls due to humidity and pests.',
      explanationUr: 'زیادہ نمی اور کیڑوں کی وجہ سے کپاس کے ٹینڈوں کا گلنا۔',
      pesticideBrand: 'Aliette',
      pesticideBrandUr: 'ایلیٹ',
      pricePkr: 2800,
      mixingRatio: '250g / 100L water',
      mixingRatioUr: '250 گرام فی 100 لیٹر پانی',
      sprayTime: 'During high humidity',
      sprayTimeUr: 'زیادہ نمی کے وقت',
      yieldLossPercent: '10% - 30%',
      financialLossPkr: 45000,
      warningSigns: ['Water-soaked bolls', 'Darkening bolls', 'Fungal growth'],
      warningSignsUr: ['پانی بھرے ٹینڈے', 'ٹینڈوں کا کالا ہونا', 'الی کا لگنا'],
    },
    'Whitefly damage': {
      nameEn: 'Whitefly damage',
      nameUr: 'سفید مکھی کا نقصان',
      explanation: 'Sap sucking pest causing honeydew and sootymold.',
      explanationUr: 'رس چوسنے والے کیڑے جو چپچپا مادہ چھوڑتے ہیں جس سے کالی الی لگتی ہے۔',
      pesticideBrand: 'Movento',
      pesticideBrandUr: 'مووینٹو',
      pricePkr: 3500,
      mixingRatio: '125ml / Acre',
      mixingRatioUr: '125 ملی لیٹر فی ایکڑ',
      sprayTime: 'Under leaves',
      sprayTimeUr: 'پتوں کے نیچے',
      yieldLossPercent: '20% - 50%',
      financialLossPkr: 80000,
      warningSigns: ['Sticky leaves', 'Black mold', 'White tiny insects'],
      warningSignsUr: ['چپچپاہٹ والے پتے', 'کالی الی', 'سفید چھوٹے کیڑے'],
    },
  },
  sugarcane: {
    'Red Rot': {
      nameEn: 'Red Rot',
      nameUr: 'رتہ روگ',
      explanation: 'Reddening of internal pith with white cross bands.',
      explanationUr: 'گنے کے اندرونی حصے کا سرخ ہونا اور سفید دھاریاں بننا۔',
      pesticideBrand: 'Dithane M-45',
      pesticideBrandUr: 'ڈائتھین ایم 45',
      pricePkr: 1350,
      mixingRatio: 'Set treatment (0.25%)',
      mixingRatioUr: 'خوری کا علاج (0.25%)',
      sprayTime: 'Before planting',
      sprayTimeUr: 'کاشت سے پہلے',
      yieldLossPercent: '25% - 50%',
      financialLossPkr: 55000,
      warningSigns: ['Third or fourth leaf drying', 'Alcoholic smell from stem', 'Internal red tissues'],
      warningSignsUr: ['تیسرے چوتھے پتے کا سوکھنا', 'تنے سے شراب جیسی بو', 'تنے کے اندر سرخ رنگ'],
    },
    'Smut': {
      nameEn: 'Smut',
      nameUr: 'کماد کی کانی',
      explanation: 'Black whip-like structure emerging from apex.',
      explanationUr: 'گنے کے اوپر سے کالی چھڑی جیسی لمبی شاخ نکلنا۔',
      pesticideBrand: 'Bayleton',
      pesticideBrandUr: 'بیلیٹان',
      pricePkr: 2200,
      mixingRatio: 'Set dipping (0.1%)',
      mixingRatioUr: 'خوری ڈبونا (0.1%)',
      sprayTime: 'Early growth',
      sprayTimeUr: 'ابتدائی نشوونما',
      yieldLossPercent: '10% - 25%',
      financialLossPkr: 30000,
      warningSigns: ['Black dusty whip', 'Grassy shoots', 'Thin stalks'],
      warningSignsUr: ['کالی خاکستری چھڑی', 'گھاس جیسی شاخیں', 'باریک تنے'],
    },
    'Ratoon Stunting': {
      nameEn: 'Ratoon Stunting',
      nameUr: 'مونڈھی کا بونا پن',
      explanation: 'Stunted growth and poor tillering.',
      explanationUr: 'کماد کی نشوونما کا رک جانا اور شاخوں کا کم نکلنا۔',
      pesticideBrand: 'Hot water treatment',
      pesticideBrandUr: 'گرم پانی کا علاج',
      pricePkr: 500,
      mixingRatio: '50°C for 2 hours',
      mixingRatioUr: '50 ڈگری پر 2 گھنٹے',
      sprayTime: 'Seed stage',
      sprayTimeUr: 'بیج کا مرحلہ',
      yieldLossPercent: '15% - 30%',
      financialLossPkr: 40000,
      warningSigns: ['Slower growth', 'Short internodes', 'Discolored vascular bundles'],
      warningSignsUr: ['کم رفتار نشوونما', 'پور کا چھوٹا ہونا', 'رگوں کا رنگ بدلنا'],
    },
    'Rust': {
      nameEn: 'Rust',
      nameUr: 'کنگئی',
      explanation: 'Elongated orange to brown pustules on leaves.',
      explanationUr: 'پتوں پر نارنجی یا بھورے رنگ کے لمبے دھبے نمودار ہونا۔',
      pesticideBrand: 'Tilt',
      pesticideBrandUr: 'ٹلٹ',
      pricePkr: 2400,
      mixingRatio: '200ml / Acre',
      mixingRatioUr: '200 ملی لیٹر فی ایکڑ',
      sprayTime: 'High humidity',
      sprayTimeUr: 'زیادہ نمی',
      yieldLossPercent: '5% - 15%',
      financialLossPkr: 20000,
      warningSigns: ['Orange leaf spots', 'Dusty leaves', 'Premature drying'],
      warningSignsUr: ['نارنجی دھبے', 'گرد آلود پتے', 'وقت سے پہلے خشک ہونا'],
    },
  },
  maize: {
    'Northern Leaf Blight': {
      nameEn: 'Northern Leaf Blight',
      nameUr: 'شمالی پتوں کا بلائٹ',
      explanation: 'Large cigar-shaped lesions on leaves.',
      explanationUr: 'پتوں پر سگار کی شکل کے بڑے لمبے نشانات بنتے ہیں۔',
      pesticideBrand: 'Priaxor',
      pesticideBrandUr: 'پرائیکسر',
      pricePkr: 4500,
      mixingRatio: '150ml / Acre',
      mixingRatioUr: '150 ملی لیٹر فی ایکڑ',
      sprayTime: 'Early morning',
      sprayTimeUr: 'صبح سویرے',
      yieldLossPercent: '20% - 50%',
      financialLossPkr: 50000,
      warningSigns: ['Long narrow lesions', 'Grayish green color', 'Dried leaves'],
      warningSignsUr: ['لمبے تنگ دھبے', 'سرمئی سبز رنگ', 'سوکھے پتے'],
    },
    'Corn Smut': {
      nameEn: 'Corn Smut',
      nameUr: 'مکئی کی کانی',
      explanation: 'Large galls on ears, stalks or leaves filled with black spores.',
      explanationUr: 'مکئی کے سٹوں، تنے یا پتوں پر کالے سفوف سے بھرے بڑے پھوڑے بننا۔',
      pesticideBrand: 'Vitavax',
      pesticideBrandUr: 'وائٹا ویکس',
      pricePkr: 1500,
      mixingRatio: 'Seed treatment (2g/kg)',
      mixingRatioUr: 'بیج کا علاج (2 گرام)',
      sprayTime: 'Tasseling',
      sprayTimeUr: 'بور آنے کے وقت',
      yieldLossPercent: '5% - 15%',
      financialLossPkr: 15000,
      warningSigns: ['White fleshy galls', 'Black spore dust', 'Deformed ears'],
      warningSignsUr: ['سفید گوشت نما پھوڑے', 'کالا سفوف', 'بگڑی ہوئی چھلیاں'],
    },
    'Stalk Rot': {
      nameEn: 'Stalk Rot',
      nameUr: 'تنے کا گلنا',
      explanation: 'Internal decay of maize stalks.',
      explanationUr: 'مکئی کے تنے کا اندر سے گل کر کھوکھلا ہو جانا۔',
      pesticideBrand: 'Tricho-P',
      pesticideBrandUr: 'ٹرائیکو پی',
      pricePkr: 1200,
      mixingRatio: 'Soil application',
      mixingRatioUr: 'زمین میں ڈالیں',
      sprayTime: 'Pre-tasseling',
      sprayTimeUr: 'بور آنے سے پہلے',
      yieldLossPercent: '10% - 30%',
      financialLossPkr: 30000,
      warningSigns: ['Premature leaf drying', 'Pith disintegration', 'Lodging'],
      warningSignsUr: ['پتوں کا سوکھنا', 'تنے کا اندر سے کھوکھلا ہونا', 'پودوں کا گرنا'],
    },
    'Downy Mildew': {
      nameEn: 'Downy Mildew',
      nameUr: 'ڈاؤنی ملڈیو',
      explanation: 'Chlorotic stripes and white downy growth on leaves.',
      explanationUr: 'پتوں پر پیلی دھاریاں اور سفید روئی جیسی الی کا اگنا۔',
      pesticideBrand: 'Curzate',
      pesticideBrandUr: 'کرزیٹ',
      pricePkr: 2000,
      mixingRatio: '500g / Acre',
      mixingRatioUr: '500 گرام فی ایکڑ',
      sprayTime: 'High humidity mornings',
      sprayTimeUr: 'نمی والی صبح',
      yieldLossPercent: '20% - 40%',
      financialLossPkr: 40000,
      warningSigns: ['Chlorotic patches', 'White fungal growth', 'Deformed leaves'],
      warningSignsUr: ['زرد دھبے', 'سفید الی', 'پتوں کی خرابی'],
    },
  },
  tomato: {
    'Early Blight': {
      nameEn: 'Early Blight',
      nameUr: 'اگیتا جھلساؤ',
      explanation: 'Target-like spots on older leaves.',
      explanationUr: 'پرانے پتوں پر گول دائروں والے دھبے بننا۔',
      pesticideBrand: 'Cabrio Top',
      pesticideBrandUr: 'کیبریو ٹاپ',
      pricePkr: 3500,
      mixingRatio: '500g / Acre',
      mixingRatioUr: '500 گرام فی ایکڑ',
      sprayTime: 'Evening',
      sprayTimeUr: 'شام',
      yieldLossPercent: '20% - 30%',
      financialLossPkr: 80000,
      warningSigns: ['Bullseye spots', 'Lower leaf yellowing', 'Stem lesions'],
      warningSignsUr: ['دائروں والے دھبے', 'نیچے کے پتوں کا پیلا ہونا', 'تنے پر نشان'],
    },
    'Late Blight': {
      nameEn: 'Late Blight',
      nameUr: 'پچھیتا جھلساؤ',
      explanation: 'Water-soaked spots growing rapidly in cool, wet weather.',
      explanationUr: 'ٹھنڈے اور گیلے موسم میں تیزی سے پھیلنے والے پانی بھرے دھبے۔',
      pesticideBrand: 'Melody Duo',
      pesticideBrandUr: 'میلوڈی ڈیو',
      pricePkr: 2900,
      mixingRatio: '250g / 100L water',
      mixingRatioUr: '250 گرام فی 100 لیٹر پانی',
      sprayTime: 'During rains',
      sprayTimeUr: 'بارشوں کے وقت',
      yieldLossPercent: '40% - 80%',
      financialLossPkr: 200000,
      warningSigns: ['Watery dark spots', 'White fuzzy growth', 'Fruit browning'],
      warningSignsUr: ['پانی بھرے دھبے', 'سفید روئی جیسی الی', 'پھل کا بھورا ہونا'],
    },
    'Tomato Mosaic Virus': {
      nameEn: 'Tomato Mosaic Virus',
      nameUr: 'موزیک وائرس',
      explanation: 'Mottling and distortion of leaves.',
      explanationUr: 'پتوں کا چتکبرا ہونا اور ان کی شکل کا بگڑ جانا۔',
      pesticideBrand: 'Imidacloprid (for vectors)',
      pesticideBrandUr: 'امیڈا کلوپرڈ',
      pricePkr: 1600,
      mixingRatio: '200ml / Acre',
      mixingRatioUr: '200 ملی لیٹر فی ایکڑ',
      sprayTime: 'Early morning',
      sprayTimeUr: 'صبح سویرے',
      yieldLossPercent: '10% - 40%',
      financialLossPkr: 100000,
      warningSigns: ['Green mottling', 'Stringy leaves', 'Stunted plant'],
      warningSignsUr: ['سبز چتکبرا پن', 'پتوں کا باریک ہونا', 'پودے کا رک جانا'],
    },
    'Fusarium Wilt': {
      nameEn: 'Fusarium Wilt',
      nameUr: 'اکھیڑا',
      explanation: 'One-sided yellowing and wilting of the plant.',
      explanationUr: 'پودے کا ایک طرف سے پیلا ہونا اور مرجھا جانا۔',
      pesticideBrand: 'Topsin-M',
      pesticideBrandUr: 'ٹاپسن ایم',
      pricePkr: 2200,
      mixingRatio: '400g / Acre (Soil)',
      mixingRatioUr: '400 گرام زمین میں',
      sprayTime: 'Before flowering',
      sprayTimeUr: 'پھول آنے سے پہلے',
      yieldLossPercent: '15% - 40%',
      financialLossPkr: 120000,
      warningSigns: ['Lower leaf yellowing', 'Wilting at noon', 'Brown stem interior'],
      warningSignsUr: ['نیچے کے پتے زرد ہونا', 'دوپہر کو مرجھانا', 'تنے کے اندر بھورا پن'],
    },
  },
  potato: {
    'Late Blight': {
      nameEn: 'Late Blight',
      nameUr: 'پچھیتا جھلساؤ',
      explanation: 'Serious disease causing rapid leaf kill and tuber rot.',
      explanationUr: 'سنگین بیماری جو پتوں کو تیزی سے ختم کرتی ہے اور آلوؤں کو گال دیتی ہے۔',
      pesticideBrand: 'Revus (Syngenta)',
      pesticideBrandUr: 'ریوس (سینجنٹا)',
      pricePkr: 4200,
      mixingRatio: '250ml / Acre',
      mixingRatioUr: '250 ملی لیٹر فی ایکڑ',
      sprayTime: 'High humidity',
      sprayTimeUr: 'زیادہ نمی',
      yieldLossPercent: '40% - 100%',
      financialLossPkr: 300000,
      warningSigns: ['Dark water-soaked lesions', 'White fuzz on underside', 'Rapid plant collapse'],
      warningSignsUr: ['پانی بھرے گہرے دھبے', 'پتے کے نیچے سفید الی', 'پودے کا اچانک مرنا'],
    },
    'Early Blight': {
      nameEn: 'Early Blight',
      nameUr: 'اگیتا جھلساؤ',
      explanation: 'Brown spots with concentric rings.',
      explanationUr: 'بھورے دھبے جن میں گول دائرے بنے ہوتے ہیں۔',
      pesticideBrand: 'Daconil',
      pesticideBrandUr: 'ڈیکونل',
      pricePkr: 2600,
      mixingRatio: '500g / Acre',
      mixingRatioUr: '500 گرام فی ایکڑ',
      sprayTime: 'Regular interval',
      sprayTimeUr: 'باقاعدگی سے',
      yieldLossPercent: '10% - 25%',
      financialLossPkr: 60000,
      warningSigns: ['Targets spots', 'Lower leaf drying', 'Stunted growth'],
      warningSignsUr: ['دائرے والے دھبے', 'نیچے کے پتوں کا خشک ہونا', 'کمزور نشوونما'],
    },
    'Black Scurf': {
      nameEn: 'Black Scurf',
      nameUr: 'کالا داغ',
      explanation: 'Fungal growth forming black scurf on tubers.',
      explanationUr: 'آلوؤں کی جلد پر کالے رنگ کے ابھرے ہوئے داغ بننا۔',
      pesticideBrand: 'Moncut',
      pesticideBrandUr: 'مان کٹ',
      pricePkr: 3300,
      mixingRatio: 'Tuber treatment',
      mixingRatioUr: 'آلو کے بیج کا علاج',
      sprayTime: 'Planting',
      sprayTimeUr: 'کاشت کے وقت',
      yieldLossPercent: '5% - 20%',
      financialLossPkr: 40000,
      warningSigns: ['Black spots on potatoes', 'Sprout kill', 'Aerial tubers'],
      warningSignsUr: ['آلو پر کالے نشان', 'شاخوں کا مرنا', 'ہوا میں چھوٹے آلو'],
    },
    'Common Scab': {
      nameEn: 'Common Scab',
      nameUr: 'سکب',
      explanation: 'Rough corky lesions on tuber surface.',
      explanationUr: 'آلو کی جلد پر کھردری اور سخت تہہ بن جانا۔',
      pesticideBrand: 'Sulfur 80% WD',
      pesticideBrandUr: 'سلفر 80% ڈبلیو ڈی',
      pricePkr: 1100,
      mixingRatio: '2kg / Acre (Soil)',
      mixingRatioUr: '2 کلو زمین میں',
      sprayTime: 'Tuberization',
      sprayTimeUr: 'آلو بننے کے دوران',
      yieldLossPercent: '5% - 10%',
      financialLossPkr: 30000,
      warningSigns: ['Corky skin', 'Pitted lesions', 'Reduced market value'],
      warningSignsUr: ['کھردری جلد', 'گھرے نشان', 'قیمت میں کمی'],
    },
  },
  onion: {
    'Purple Blotch': {
      nameEn: 'Purple Blotch',
      nameUr: 'ارغوانی دھبہ',
      explanation: 'Purple-centered lesions on leaves and flower stalks.',
      explanationUr: 'پتوں اور پھولوں کی ڈنڈیوں پر جامنی رنگ کے دھبے بننا۔',
      pesticideBrand: 'Ridomil Gold',
      pesticideBrandUr: 'ریڈومل گولڈ',
      pricePkr: 3800,
      mixingRatio: '250g / 100L water',
      mixingRatioUr: '250 گرام 100 لیٹر پانی میں',
      sprayTime: 'During rain season',
      sprayTimeUr: 'بارشوں میں',
      yieldLossPercent: '20% - 50%',
      financialLossPkr: 70000,
      warningSigns: ['Purple spots', 'Leaf breaking', 'Secondary rot'],
      warningSignsUr: ['ارغوانی دھبے', 'پتوں کا ٹوٹنا', 'گلن سڑن'],
    },
    'Downy Mildew': {
      nameEn: 'Downy Mildew',
      nameUr: 'ڈاؤنی ملڈیو',
      explanation: 'Purple velvety growth on leaves.',
      explanationUr: 'پتوں پر مخملی جامنی رنگ کی الی کا اگنا۔',
      pesticideBrand: 'Infinito (Bayer)',
      pesticideBrandUr: 'انفینیٹو',
      pricePkr: 3100,
      mixingRatio: '600ml / Acre',
      mixingRatioUr: '600 ملی لیٹر فی ایکڑ',
      sprayTime: 'Morning moisture',
      sprayTimeUr: 'نمی والی صبح',
      yieldLossPercent: '15% - 30%',
      financialLossPkr: 50000,
      warningSigns: ['Grayish violet mold', 'Yellowing leaves', 'Drying leaf tips'],
      warningSignsUr: ['سرمئی الی', 'پتوں کی زردی', 'پتوں کے نوکوں کا خشک ہونا'],
    },
    'Fusarium Basal Rot': {
      nameEn: 'Fusarium Basal Rot',
      nameUr: 'نیچے سے گلنا',
      explanation: 'Decay of basal plate and roots.',
      explanationUr: 'پیاز کے نچلے حصے اور جڑوں کا گلنا۔',
      pesticideBrand: 'Copper Oxychloride',
      pesticideBrandUr: 'کاپر آکسی کلورائیڈ',
      pricePkr: 1400,
      mixingRatio: '500g / Acre',
      mixingRatioUr: '500 گرام فی ایکڑ',
      sprayTime: 'In irrigation',
      sprayTimeUr: 'پانی کے ساتھ',
      yieldLossPercent: '10% - 25%',
      financialLossPkr: 40000,
      warningSigns: ['Premature leaf yellowing', 'Root decay', 'White mold on base'],
      warningSignsUr: ['پتوں کا سوکھنا', 'جڑوں کا گلنا', 'نیچے سفید الی'],
    },
    'Thrips damage': {
      nameEn: 'Thrips damage',
      nameUr: 'تھرپس کا حملہ',
      explanation: 'Small insects sucking sap causing silvery streaks.',
      explanationUr: 'چھوٹے کیڑے جو رس چوستے ہیں اور پتوں پر چاندی کی لکیریں بناتے ہیں۔',
      pesticideBrand: 'Radiant',
      pesticideBrandUr: 'ریڈینٹ',
      pricePkr: 4400,
      mixingRatio: '100ml / Acre',
      mixingRatioUr: '100 ملی لیٹر فی ایکڑ',
      sprayTime: 'Full coverage',
      sprayTimeUr: 'مکمل اسپرے',
      yieldLossPercent: '20% - 40%',
      financialLossPkr: 80000,
      warningSigns: ['Silvery streaks on leaves', 'Thickened leaves', 'Stunted bulbs'],
      warningSignsUr: ['چاندی نما لکیریں', 'پتوں کا موٹا ہونا', 'گٹھی کا چھوٹا ہونا'],
    },
  },
  chilli: {
    'Anthracnose': {
      nameEn: 'Anthracnose',
      nameUr: 'پھل کا گلنا',
      explanation: 'Sunken lesions on chilli pods.',
      explanationUr: 'مرچوں پر اندر کی طرف دبے ہوئے دھبے بننا۔',
      pesticideBrand: 'Kumulus',
      pesticideBrandUr: 'کومولس',
      pricePkr: 1250,
      mixingRatio: '2kg / Acre',
      mixingRatioUr: '2 کلو فی ایکڑ',
      sprayTime: 'Fruit setting',
      sprayTimeUr: 'پھل لگنے کے وقت',
      yieldLossPercent: '20% - 50%',
      financialLossPkr: 150000,
      warningSigns: ['Circular dark spots on fruit', 'Premature fruit fall', 'Seed rot'],
      warningSignsUr: ['پھل پر گول کالے دھبے', 'پھل کا گرنا', 'بیجوں کی خرابی'],
    },
    'Chilli Leaf Curl Virus': {
      nameEn: 'Chilli Leaf Curl Virus',
      nameUr: 'پتہ مروڑ وائرس',
      explanation: 'Severe curling and dwarfing of the plant.',
      explanationUr: 'پتوں کا شدید مڑنا اور پودے کا قد چھوٹا رہنا۔',
      pesticideBrand: 'Actara',
      pesticideBrandUr: 'ایکٹارل',
      pricePkr: 2000,
      mixingRatio: '24g / Acre',
      mixingRatioUr: '24 گرام فی ایکڑ',
      sprayTime: 'At pest sighting',
      sprayTimeUr: 'کیڑا دکھنے پر',
      yieldLossPercent: '30% - 100%',
      financialLossPkr: 250000,
      warningSigns: ['Curling leaves', 'Stunted grow', 'Absence of fruit'],
      warningSignsUr: ['مڑے ہوئے پتے', 'بونا پودا', 'پھل نہ لگنا'],
    },
    'Phytophthora Blight': {
      nameEn: 'Phytophthora Blight',
      nameUr: 'جھلساؤ',
      explanation: 'Sudden wilting and dark lesions on stem.',
      explanationUr: 'پودے کا اچانک مرجھانا اور تنے پر سیاہ نشانات۔',
      pesticideBrand: 'Curzate M-8',
      pesticideBrandUr: 'کرزیٹ ایم 8',
      pricePkr: 1800,
      mixingRatio: '500g / Acre',
      mixingRatioUr: '500 گرام فی ایکڑ',
      sprayTime: 'Monsoon',
      sprayTimeUr: 'مون سون',
      yieldLossPercent: '20% - 60%',
      financialLossPkr: 180000,
      warningSigns: ['Water-soaked stem', 'Rapid wilting', 'Fruit rot'],
      warningSignsUr: ['پانی بھرا تنا', 'شدید مرجھانا', 'پھل کا گلنا'],
    },
    'Bacterial Wilt': {
      nameEn: 'Bacterial Wilt',
      nameUr: 'مرجھاؤ',
      explanation: 'Systemic wilting caused by bacteria.',
      explanationUr: 'بیکٹیریا کی وجہ سے پودے کا تیزی سے مرجھانا۔',
      pesticideBrand: 'Streptocycline',
      pesticideBrandUr: 'اسٹریپٹو مائیسن',
      pricePkr: 600,
      mixingRatio: '6g / 15L water',
      mixingRatioUr: '6 گرام فی 15 لیٹر',
      sprayTime: 'Early morning',
      sprayTimeUr: 'صبح سویرے',
      yieldLossPercent: '15% - 40%',
      financialLossPkr: 100000,
      warningSigns: ['Sudden droop', 'Green wilted leaves', 'Bacterial ooze from stem'],
      warningSignsUr: ['اچانک سوکھنا', 'ہرے پتوں کا لٹکنا', 'تنے سے سفید رطوبت'],
    },
  },
  mango: {
    'Anthracnose': {
      nameEn: 'Anthracnose',
      nameUr: 'اینتھراکنوز',
      explanation: 'Dark brown spots on leaves and fruit.',
      explanationUr: 'آم کے پتوں اور پھل پر گہرے بھورے دھبے بننا۔',
      pesticideBrand: 'Nativo',
      pesticideBrandUr: 'نیٹیوو',
      pricePkr: 4500,
      mixingRatio: '65g / 100L water',
      mixingRatioUr: '65 گرام فی 100 لیٹر',
      sprayTime: 'During flowering',
      sprayTimeUr: 'بور آنے کے وقت',
      yieldLossPercent: '20% - 30%',
      financialLossPkr: 200000,
      warningSigns: ['Black spots on mango', 'Leaf blight', 'Flower drop'],
      warningSignsUr: ['آم پر کالے دھبے', 'پتوں کا سڑنا', 'بور کا گرنا'],
    },
    'Powdery Mildew': {
      nameEn: 'Powdery Mildew',
      nameUr: 'سفیدک',
      explanation: 'White powdery growth on flowers and fruits.',
      explanationUr: 'پتوں اور تنے پر سفید پاؤڈر جیسے دھبے نمودار ہوتے ہیں۔',
      pesticideBrand: 'Sulfur 80% DP',
      pesticideBrandUr: 'سلفر 80%',
      pricePkr: 1400,
      mixingRatio: '2kg / Acre',
      mixingRatioUr: '2 کلو فی ایکڑ',
      sprayTime: 'Inflorescence stage',
      sprayTimeUr: 'بور کے وقت',
      yieldLossPercent: '15% - 50%',
      financialLossPkr: 300000,
      warningSigns: ['White dust on flowers', 'Drying of panicles', 'Small fruit drop'],
      warningSignsUr: ['بور پر سفید سفوف', 'بور کا سوکھنا', 'چھوٹے پھل کا گرنا'],
    },
    'Mango Malformation': {
      nameEn: 'Mango Malformation',
      nameUr: 'گچھی روگ',
      explanation: 'Clusters of small deformed flowers.',
      explanationUr: 'پھولوں کا گچھا بن جانا اور ان کی شکل بگڑ جانا۔',
      pesticideBrand: 'Planofix (control)',
      pesticideBrandUr: 'پلانو فکس',
      pricePkr: 1200,
      mixingRatio: '200ppm spray',
      mixingRatioUr: '200 پی پی ایم',
      sprayTime: 'October/November',
      sprayTimeUr: 'اکتوبر/نومبر',
      yieldLossPercent: '10% - 60%',
      financialLossPkr: 400000,
      warningSigns: ['Bunchy top', 'Leaf-like flowers', 'No fruit set'],
      warningSignsUr: ['پتوں کا گچھا', 'پھولوں کی غیر قدرتی شکل', 'پھل نہ لگنا'],
    },
    'Stem End Rot': {
      nameEn: 'Stem End Rot',
      nameUr: 'تنے کا گلاؤ',
      explanation: 'Rotting of mango starting from stem end after harvest.',
      explanationUr: 'آم کی کٹائی کے بعد ڈنڈی والی جگہ سے پھل کا گلنا۔',
      pesticideBrand: 'Thiophanate-Methyl',
      pesticideBrandUr: 'تھیوفینیٹ میتھائل',
      pricePkr: 2500,
      mixingRatio: 'Hot water dip',
      mixingRatioUr: 'گرم پانی کا علاج',
      sprayTime: 'After harvest',
      sprayTimeUr: 'کٹائی کے بعد',
      yieldLossPercent: '5% - 20%',
      financialLossPkr: 150000,
      warningSigns: ['Soft dark stem base', 'Liquid oozing', 'Bad smell'],
      warningSignsUr: ['آم کے نیچے سے نرم ہونا', 'رطوبت کا نکلنا', 'بو کا آنا'],
    },
  },
  citrus: {
    'Citrus Canker': {
      nameEn: 'Citrus Canker',
      nameUr: 'کینکر',
      explanation: 'Raised corky spots on leaves, stems and fruit.',
      explanationUr: 'پتوں، تنے اور پھل پر ابھرے ہوئے کھردرے نشانات۔',
      pesticideBrand: 'Kocide',
      pesticideBrandUr: 'کوسائیڈ',
      pricePkr: 3200,
      mixingRatio: '250g / 100L water',
      mixingRatioUr: '250 گرام فی 100 لیٹر',
      sprayTime: 'Before rains',
      sprayTimeUr: 'بارشوں سے پہلے',
      yieldLossPercent: '10% - 25%',
      financialLossPkr: 80000,
      warningSigns: ['Rough raised spots', 'Yellow halo', 'Fruit drop'],
      warningSignsUr: ['کھردرا ابھرا ہوا نشان', 'زرد ہالہ', 'پھل کا گرنا'],
    },
    'Greening Disease': {
      nameEn: 'Greening Disease',
      nameUr: 'گریننگ (سائلس)',
      explanation: 'Fatal bacterial disease spreading via psylla.',
      explanationUr: 'تباہ کن بیکٹیریل بیماری جو سفید مکھی (سائلا) سے پھیلتی ہے۔',
      pesticideBrand: 'Fighter (insecticide)',
      pesticideBrandUr: 'فائٹر (کیڑے مار)',
      pricePkr: 1800,
      mixingRatio: '150ml / 100L water',
      mixingRatioUr: '150 ملی لیٹر',
      sprayTime: 'Growth flush',
      sprayTimeUr: 'نئی شاخیں آنے پر',
      yieldLossPercent: '20% - 70%',
      financialLossPkr: 250000,
      warningSigns: ['Yellow shoots', 'Small bitter fruit', 'Leaf mottling'],
      warningSignsUr: ['پیلی شاخیں', 'چھوٹا کڑوا پھل', 'پتوں کا چتکبرا ہونا'],
    },
    'Melanose': {
      nameEn: 'Melanose',
      nameUr: 'میلانس',
      explanation: 'Sandpaper-like spots on leaves and fruit.',
      explanationUr: 'پتوں اور پھل پر ریگ مال جیسے کھردرے دھبے بننا۔',
      pesticideBrand: 'Cuprozin',
      pesticideBrandUr: 'کیوپروزن',
      pricePkr: 2400,
      mixingRatio: '500g / Acre',
      mixingRatioUr: '500 گرام فی ایکڑ',
      sprayTime: 'Post bloom',
      sprayTimeUr: 'پھول آنے کے بعد',
      yieldLossPercent: '5% - 15%',
      financialLossPkr: 40000,
      warningSigns: ['Tea-stain pattern', 'Rough fruit surface', 'Spotted leaves'],
      warningSignsUr: ['چائے کے رنگ کے دھبے', 'پھل کا کھردرا ہونا', 'دھبے والے پتے'],
    },
    'Phytophthora Root Rot': {
      nameEn: 'Phytophthora Root Rot',
      nameUr: 'جڑوں کا گلاؤ',
      explanation: 'Decay of roots and gumming on bark.',
      explanationUr: 'جڑوں کا گلنا اور تنے سے گوند کا نکلنا۔',
      pesticideBrand: 'Aliette (Bayer)',
      pesticideBrandUr: 'ایلیٹ (بائر)',
      pricePkr: 3600,
      mixingRatio: '250g / 100L water',
      mixingRatioUr: '250 گرام فی 100 لیٹر',
      sprayTime: 'Drenching',
      sprayTimeUr: 'جڑوں میں ڈالیں',
      yieldLossPercent: '15% - 40%',
      financialLossPkr: 150000,
      warningSigns: ['Bark cracking', 'Gum secretion', 'Yellowing leaves'],
      warningSignsUr: ['چھلکا پھٹنا', 'گوند کا نکلنا', 'پتوں کی زردی'],
    },
  },
  sunflower: {
    'Downy Mildew': {
      nameEn: 'Downy Mildew',
      nameUr: 'ڈاؤنی ملڈیو',
      explanation: 'Stunted plants and white downy growth on leaf underside.',
      explanationUr: 'پودوں کا قد رکنا اور پتوں کے نیچے سفید الی کا اگنا۔',
      pesticideBrand: 'Metalaxyl',
      pesticideBrandUr: 'میٹالیکسل',
      pricePkr: 1750,
      mixingRatio: '5g / kg seed',
      mixingRatioUr: '5 گرام فی کلو بیج',
      sprayTime: 'Seed stage',
      sprayTimeUr: 'بیج کا مرحلہ',
      yieldLossPercent: '20% - 50%',
      financialLossPkr: 40000,
      warningSigns: ['Short plant', 'White leaf mold', 'Horizontal heads'],
      warningSignsUr: ['چھوٹا بونا پودا', 'پتوں پر سفید الی', 'سٹوں کا مڑنا'],
    },
    'Alternaria Blight': {
      nameEn: 'Alternaria Blight',
      nameUr: 'الٹرنیریا بلائٹ',
      explanation: 'Dark brown spots with yellow halos on leaves.',
      explanationUr: 'پتوں پر گہرے بھورے دھبے جن کے گرد زرد ہالہ ہوتا ہے۔',
      pesticideBrand: 'Score',
      pesticideBrandUr: 'اسکور',
      pricePkr: 2200,
      mixingRatio: '200ml / Acre',
      mixingRatioUr: '200 ملی لیٹر فی ایکڑ',
      sprayTime: 'After flowering',
      sprayTimeUr: 'پھول کے بعد',
      yieldLossPercent: '10% - 25%',
      financialLossPkr: 20000,
      warningSigns: ['Brown target spots', 'Reduced head size', 'Early drying'],
      warningSignsUr: ['گول بھورے نشان', 'سٹے کا چھوٹا سایز', 'وقت سے پہلے سوکھنا'],
    },
    'Rust': {
      nameEn: 'Rust',
      nameUr: 'کنگئی',
      explanation: 'Cinnamon colored pustules on leaves.',
      explanationUr: 'پتوں پر نارنجی یا بھورے رنگ کے پاؤڈر والے دھبے۔',
      pesticideBrand: 'Tilt',
      pesticideBrandUr: 'ٹلٹ',
      pricePkr: 2600,
      mixingRatio: '200ml / Acre',
      mixingRatioUr: '200 ملی لیٹر فی ایکڑ',
      sprayTime: 'High humidity',
      sprayTimeUr: 'زیادہ نمی',
      yieldLossPercent: '5% - 15%',
      financialLossPkr: 15000,
      warningSigns: ['Orange-brown spots', 'Cracking leaves', 'Plant weakness'],
      warningSignsUr: ['کنگئی جیسے دھبے', 'پتوں کا پھٹنا', 'پودے کی کمزوری'],
    },
    'Charcoal Rot': {
      nameEn: 'Charcoal Rot',
      nameUr: 'چارکول روٹ',
      explanation: 'Soil-borne disease causing stem blackening and rotting.',
      explanationUr: 'زمین سے پیدا ہونے والی بیماری جو تنے کو کالا کر کے گال دیتی ہے۔',
      pesticideBrand: 'Seed Treatment',
      pesticideBrandUr: 'بیج کا زہر',
      pricePkr: 900,
      mixingRatio: 'Seed treatment',
      mixingRatioUr: 'بیج کا علاج',
      sprayTime: 'Drought stress',
      sprayTimeUr: 'خشکی کے وقت',
      yieldLossPercent: '15% - 30%',
      financialLossPkr: 35000,
      warningSigns: ['Stem shredding', 'Black dust in stem', 'Premature death'],
      warningSignsUr: ['تنے کا ریشہ ریشہ ہونا', 'تنے میں کالا سفوف', 'اچانک سوکھنا'],
    },
  },
};


// I'll populate the rest of the offline data in a separate step to keep it clean.
